/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyectodeprueba.ui;

import com.formdev.flatlaf.FlatClientProperties;
import conexion.ConexionMysql;
import util.SessionManager;
import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author Pablo
 */
public class HomePanel extends javax.swing.JPanel {
    
    private MainFrame parent;

    /**
     * Creates new form HomePanel
     */
    public HomePanel(MainFrame parent) {
        initComponents();
        this.parent = parent;
        
        // Estilos del botón
        btnLogs.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        
        btnAsistencias.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        
        btnEmpleados.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        
        btnNomina.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        
        btnAdmin.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        
        btnLogout.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        
        // NUEVO: Configurar interface según rol del usuario
        configurarInterfazPorRol();
    }
    
    /**
     * Configura la interfaz según el rol del usuario actual
     * - Admin: Ve botón "Admin Sistema"
     * - Capturista: Ve botón "Prestaciones" 
     * - Actualiza lblUser con nombre real
     */
    private void configurarInterfazPorRol() {



        if (SessionManager.haySesionActiva()) {

        }
        
        // Actualizar nombre del usuario en lblUser
        if (SessionManager.haySesionActiva()) {
            lblUser.setText("Usuario: " + SessionManager.getNombreUsuario());
        }
        
        // Configurar botón según rol
        if (SessionManager.esAdmin()) {
            // Para admin: asegurar que dice "Admin Sistema" y está visible
            btnAdmin.setText("Admin Sistema");
            btnAdmin.setVisible(true);
            
            // Quitar listeners anteriores
            for (ActionListener listener : btnAdmin.getActionListeners()) {
                btnAdmin.removeActionListener(listener);
            }
            
            // Acción para ir a admin sistema
            btnAdmin.addActionListener(e -> parent.showPanel("adminsistema"));

            
        } else if (SessionManager.esCapturista()) {
            // Para capturistas: cambiar botón Admin por Prestaciones
            btnAdmin.setText("Prestaciones");
            btnAdmin.setVisible(true);
            
            // Quitar listeners anteriores
            for (ActionListener listener : btnAdmin.getActionListeners()) {
                btnAdmin.removeActionListener(listener);
            }
            
            // Agregar nueva acción para ir a prestaciones
            btnAdmin.addActionListener(e -> parent.showPanel("prestaciones"));

            
        } else {
            // Si no es admin ni capturista, ocultar botón
            btnAdmin.setVisible(false);

        }
    }


    public void setUsuario(String usuario) {
        // ACTUALIZADO: Usar SessionManager si hay sesión activa
        if (SessionManager.haySesionActiva()) {
            lblUser.setText("Usuario: " + SessionManager.getNombreUsuario());
        } else {
            lblUser.setText("Usuario: " + usuario);
        }
    }
    
    /**
     * Método público para reconfigurar la interfaz cuando el panel se activa
     * Útil si el panel se crea antes de que inicie sesión
     */
    public void actualizarInterfaz() {
        configurarInterfazPorRol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBar = new javax.swing.JPanel();
        userLogo = new javax.swing.JLabel();
        panelOcmLogo = new javax.swing.JPanel();
        ocmLogo = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnLogs = new javax.swing.JButton();
        btnAsistencias = new javax.swing.JButton();
        infoLogo = new javax.swing.JLabel();
        btnEmpleados = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnNomina = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBar.setBackground(new java.awt.Color(55, 55, 55));
        topBar.setRequestFocusEnabled(false);
        topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person.png"))); // NOI18N
        topBar.add(userLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        panelOcmLogo.setBackground(new java.awt.Color(255, 255, 255));
        panelOcmLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ocmLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ocmLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_home.png"))); // NOI18N
        panelOcmLogo.add(ocmLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        topBar.add(panelOcmLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 240, 75));

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topBar.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 30));

        add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 100));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Seleccione una opción:");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 400, 40));

        btnLogs.setBackground(new java.awt.Color(228, 68, 28));
        btnLogs.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnLogs.setForeground(new java.awt.Color(255, 255, 255));
        btnLogs.setText("Logs");
        btnLogs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });
        add(btnLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 250, 140));

        btnAsistencias.setBackground(new java.awt.Color(228, 68, 28));
        btnAsistencias.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnAsistencias.setForeground(new java.awt.Color(255, 255, 255));
        btnAsistencias.setText("Asistencia");
        btnAsistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciasActionPerformed(evt);
            }
        });
        add(btnAsistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 250, 140));

        infoLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info_logo.png"))); // NOI18N
        add(infoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 400, -1));

        btnEmpleados.setBackground(new java.awt.Color(228, 68, 28));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setText("Empleados");
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 240, 150));

        btnLogout.setBackground(new java.awt.Color(228, 68, 28));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Cerrar Sesión");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, 240, 140));

        btnAdmin.setBackground(new java.awt.Color(228, 68, 28));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setText("Admin. Sistema");
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 250, 140));

        btnNomina.setBackground(new java.awt.Color(228, 68, 28));
        btnNomina.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnNomina.setForeground(new java.awt.Color(255, 255, 255));
        btnNomina.setText("Nómina");
        btnNomina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNominaActionPerformed(evt);
            }
        });
        add(btnNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 250, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciasActionPerformed
        // TODO add your handling code here:
      
        parent.showPanel("asistencias");

    }//GEN-LAST:event_btnAsistenciasActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        parent.showPanel("empleados");
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNominaActionPerformed
        // TODO add your handling code here:
        parent.showPanel("nomina");
    }//GEN-LAST:event_btnNominaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // Cerrar sesión (limpiar variables de sesión en mysql)
        SessionManager.cerrarSesion();
        
        // Cerrar la conexion a la base de datos
        ConexionMysql.cerrarConexion();
        
        // Ir a Login
        parent.showPanel("login");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        parent.showPanel("adminsistema");
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        // TODO add your handling code here:
        parent.showPanel("logs");
    }//GEN-LAST:event_btnLogsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAsistencias;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnNomina;
    private javax.swing.JLabel infoLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel ocmLogo;
    private javax.swing.JPanel panelOcmLogo;
    private javax.swing.JPanel topBar;
    private javax.swing.JLabel userLogo;
    // End of variables declaration//GEN-END:variables
}
