/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyectodeprueba.ui;

import com.formdev.flatlaf.FlatClientProperties;
import DAO.UsuarioDAO;
import models.Usuario;
import util.SessionManager;

/**
 *
 * @author Pablo
 */
public class LoginPanel extends javax.swing.JPanel {
    
    private MainFrame parent;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(MainFrame parent) {
        initComponents();
        this.parent = parent;
        
        // Redondear esquinas txts
        txtUsername.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtPassword.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        
        // Placeholder txts
        txtUsername.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Usuario");
        txtPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Contraseña");
        
        // Estilos del botón
        btnLogin.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        btnLogin.putClientProperty(FlatClientProperties.BUTTON_TYPE, "roundRect");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        rPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 7.png"))); // NOI18N
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -20, 800, 600));

        rPanel.setBackground(new java.awt.Color(55, 55, 55));
        rPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Bienvenido Usuario!");
        rPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 400, -1));
        rPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 300, 40));
        rPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 300, 40));

        btnLogin.setBackground(new java.awt.Color(228, 68, 28));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        rPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 120, 40));

        add(rPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 630, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String userGetted = txtUsername.getText();
    String passGetted = new String(txtPassword.getPassword());
    
    if (userGetted.isEmpty() || passGetted.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese usuario y contraseña.", "Campos Vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    
    if (UsuarioDAO.autenticarUsuario(userGetted, passGetted)) {
        // Si la autenticación es exitosa...
        
        // NUEVO: Obtener datos completos del usuario
        Usuario usuarioCompleto = UsuarioDAO.obtenerUsuarioCompleto(userGetted);
        
        if (usuarioCompleto != null) {
            // NUEVO: Iniciar sesión con SessionManager
            SessionManager.iniciarSesion(usuarioCompleto);
            
            // Actualizar MainFrame con nombre real del usuario
            parent.actualizarUsuario(SessionManager.getNombreUsuario());
            
            // Navegar al panel home
            parent.showPanel("home");
            
            // Limpiar formulario
            txtUsername.setText("");
            txtPassword.setText("");
            

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al obtener datos del usuario.", 
                "Error del Sistema", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Usuario o contraseña incorrectos.", 
            "Error de Autenticación", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel rPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
