/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyectodeprueba.ui;

import java.awt.CardLayout;
import java.awt.Color;
import util.SessionManager;

/**
 *
 * @author Pablo
 */
public class MainFrame extends javax.swing.JFrame {
    
    private int xMouse, yMouse;
    private HomePanel homePanel;
    private AsistenciasPanel asistenciasPanel;
    private EmpleadosPanel empleadosPanel;
    private NominaPanel nominaPanel;
    private AdminSistemaPanel adminsistemaPanel;
    private LogsPanel logsPanel;
    private PrestacionesPanel prestacionesPanel;
   

    /**
     * Creates new form HomeFrame
     */
    public MainFrame() {
        initComponents();
        
        LoginPanel loginPanel = new LoginPanel(this);
        mainPanel.add(loginPanel, "login");
        
        homePanel = new HomePanel(this);
        mainPanel.add(homePanel, "home");
        
          asistenciasPanel = new AsistenciasPanel(this);
          mainPanel.add(asistenciasPanel, "asistencias"); 
          
          empleadosPanel = new EmpleadosPanel(this);
          mainPanel.add(empleadosPanel, "empleados");
          
          nominaPanel = new NominaPanel(this);
          mainPanel.add(nominaPanel, "nomina");
          
          adminsistemaPanel = new AdminSistemaPanel(this);
          mainPanel.add(adminsistemaPanel, "adminsistema");
          
          logsPanel = new LogsPanel(this);
          mainPanel.add(logsPanel, "logs");
          
          prestacionesPanel = new PrestacionesPanel(this);
          mainPanel.add(prestacionesPanel, "prestaciones");

        
        showPanel("login");
    }
    
    public void showPanel(String name) {
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, name);
        
        // NUEVO: Actualizar interfaz del panel según rol después de mostrarlo
        switch (name) {
            case "home":
                if (homePanel != null) homePanel.actualizarInterfaz();
                break;
            case "empleados":
                if (empleadosPanel != null) empleadosPanel.actualizarInterfaz();
                break;
            case "asistencias":
                if (asistenciasPanel != null) asistenciasPanel.actualizarInterfaz();
                break;
            case "nomina":
                if (nominaPanel != null) nominaPanel.actualizarInterfaz();
                break;
            case "logs":
                if (logsPanel != null) logsPanel.actualizarInterfaz();
                break;
            case "adminsistema":
                if (adminsistemaPanel != null) adminsistemaPanel.actualizarInterfaz();
                break;
            case "prestaciones":
                if (prestacionesPanel != null) prestacionesPanel.actualizarInterfaz();
                break;
        }
    }

    public void actualizarUsuario(String usuario) {
        homePanel.setUsuario(usuario);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBar = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBar.setBackground(new java.awt.Color(55, 55, 55));
        topBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topBarMouseDragged(evt);
            }
        });
        topBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topBarMousePressed(evt);
            }
        });
        topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(55, 55, 55));
        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(true);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        topBar.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 50, 30));

        getContentPane().add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 30));

        mainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setBackground(Color.decode("#373737"));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void topBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topBarMousePressed

    private void topBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_topBarMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel topBar;
    // End of variables declaration//GEN-END:variables
}
