/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyectodeprueba.ui.subventanas;


import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.JOptionPane;
import models.Asistencia;
import DAO.AsistenciaDAO;

/**
 *
 * @author Pablo
 */
public class AgregarAsistenciaPanel extends javax.swing.JPanel {
    
    private AgregarDialog parentDialog; // Cambié ModificaDialog por AgregarDialog
    private Runnable onUpdateSuccess;
    
    
    /**
     * Creates new form CrearAsistenciaPanel
     */
    public AgregarAsistenciaPanel(AgregarDialog parent, Runnable onUpdate) { // Agregué el parámetro Runnable
        parentDialog = parent;
        this.onUpdateSuccess = onUpdate; // Solo estas dos líneasinitComponents();
        this.parentDialog = parent;
        this.onUpdateSuccess = onUpdate; // Solo estas dos líneas
        initComponents();
        
        // Estilos de los componentes (tu código original)
        txtHoras.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtId.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        btnAgregar.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        btnAgregar.putClientProperty(FlatClientProperties.BUTTON_TYPE, "roundRect");
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(55, 55, 55));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jLabel1.setBackground(new java.awt.Color(55, 55, 55));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Asistencia");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 240));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Horas Trabajadas:");
        jLabel2.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel5.add(jLabel2);

        txtHoras.setBackground(new java.awt.Color(216, 216, 216));
        txtHoras.setPreferredSize(new java.awt.Dimension(220, 30));
        txtHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorasActionPerformed(evt);
            }
        });
        jPanel5.add(txtHoras);

        jPanel2.add(jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Id Empleado:");
        jLabel3.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel3.add(jLabel3);

        txtId.setBackground(new java.awt.Color(216, 216, 216));
        txtId.setPreferredSize(new java.awt.Dimension(220, 30));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel3.add(txtId);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        btnAgregar.setBackground(new java.awt.Color(55, 55, 55));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setPreferredSize(new java.awt.Dimension(80, 35));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        jPanel4.add(btnAgregar);

        jPanel2.add(jPanel4);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here: 
        
        try {
        // Validar campos
        String idStr = txtId.getText().trim();
        String horasStr = txtHoras.getText().trim();

        if (idStr.isEmpty() || horasStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idEmpleado = Integer.parseInt(idStr);
        int horasTrabajadas = Integer.parseInt(horasStr);

        // Crear nueva asistencia
        Asistencia nuevaAsistencia = new Asistencia();
        nuevaAsistencia.setIdEmpleado(idEmpleado);
        nuevaAsistencia.setHorasTrabajadas(horasTrabajadas);

        // Guardar en la base de datos
        AsistenciaDAO dao = new AsistenciaDAO();
        boolean exito = dao.agregarAsistencia(nuevaAsistencia);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Asistencia agregada correctamente.");
            
            // Ejecutar callback de actualización
            if (onUpdateSuccess != null) {
                onUpdateSuccess.run();
            }
            
            // Cerrar diálogo
            parentDialog.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar la asistencia.", "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese números válidos para ID y horas.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void txtHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorasActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
