/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyectodeprueba.ui.subventanas;

import DAO.AsistenciaDAO;
import DAO.EmpleadoDAO;
import DAO.NominaDAO;
import DAO.PrestacionDAO;
import com.formdev.flatlaf.FlatClientProperties;
import com.proyectodeprueba.ui.subventanas.confirmacion.ConfirmacionDialog;
import java.awt.Frame;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import models.Nomina;

/**
 *
 * @author Pablo
 */
public class AgregarNominaPanel extends javax.swing.JPanel {
    
    private AgregarDialog parent;
    private Runnable onUpdateSuccess;

    /**
     * Creates new form AgregarNominaPanel
     */
    public AgregarNominaPanel(AgregarDialog parent, Runnable onUpdate) {
        this.parent = parent;
        this.onUpdateSuccess = onUpdate;
        initComponents();
        
        txtIdEmpleado.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        
        btnAgregar.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        btnAgregar.putClientProperty(FlatClientProperties.BUTTON_TYPE, "roundRect");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(300, 200));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(55, 55, 55));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Nómina");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id Empleado:");
        jLabel2.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel3.add(jLabel2);

        txtIdEmpleado.setBackground(new java.awt.Color(216, 216, 216));
        txtIdEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        txtIdEmpleado.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel3.add(txtIdEmpleado);

        jPanel2.add(jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btnAgregar.setBackground(new java.awt.Color(55, 55, 55));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setPreferredSize(new java.awt.Dimension(80, 35));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel8.add(btnAgregar);

        jPanel2.add(jPanel8);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Crear la ventana de confirmación personalizada
        ConfirmacionDialog confirmacion = new ConfirmacionDialog((Frame) parent.getParent(), true);

        // Configurar la acción a ejecutar si el usuario confirma
        confirmacion.setOnConfirmar(() -> {
            try {
                // 1. VALIDAR CAMPO OBLIGATORIO (solo ID Empleado)
                String idEmpleadoStr = txtIdEmpleado.getText().trim();

                if (idEmpleadoStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, 
                        "ID Empleado es obligatorio", 
                        "Error de Validación", 
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // 2. CONVERTIR ID EMPLEADO A NÚMERO
                int idEmpleado = Integer.parseInt(idEmpleadoStr);
                
                // 3. VERIFICAR QUE EL EMPLEADO EXISTE Y OBTENER SU SUELDO BASE
                EmpleadoDAO empleadoDAO = new EmpleadoDAO();
                BigDecimal sueldoBaseEmpleado = empleadoDAO.obtenerSueldoBase(idEmpleado);
                
                // Validar que el empleado existe (sueldo base no debe ser 0 o null)
                if (sueldoBaseEmpleado.compareTo(BigDecimal.ZERO) == 0) {
                    JOptionPane.showMessageDialog(this, 
                        "No se encontró el empleado con ID " + idEmpleado + " o no tiene sueldo base asignado", 
                        "Empleado No Encontrado", 
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }

                // 4. CALCULAR TODOS LOS VALORES AUTOMÁTICAMENTE
                AsistenciaDAO asistenciaDAO = new AsistenciaDAO();
                PrestacionDAO prestacionDAO = new PrestacionDAO();
                
                // Calcular horas trabajadas totales del empleado
                int totalHorasTrabajadas = asistenciaDAO.calcularHorasTrabajadas(idEmpleado);
                
                // Calcular total de prestaciones del empleado
                BigDecimal totalPrestaciones = prestacionDAO.calcularTotalPrestaciones(idEmpleado);
                
                // Calcular total neto: sueldo base - prestaciones
                BigDecimal totalNeto = sueldoBaseEmpleado.subtract(totalPrestaciones);

                // 5. CREAR OBJETO NOMINA CON TODOS LOS VALORES CALCULADOS AUTOMÁTICAMENTE
                Nomina nuevaNomina = new Nomina();

                // Campo ingresado por el usuario
                nuevaNomina.setIdEmpleado(idEmpleado);
                
                // Fecha actual automática
                nuevaNomina.setFecha(LocalDateTime.now());
                
                // Todos los valores calculados automáticamente desde la BD
                nuevaNomina.setSueldoBase(sueldoBaseEmpleado);
                nuevaNomina.setTotalHorasTrabajadas(totalHorasTrabajadas);
                nuevaNomina.setTotalPrestaciones(totalPrestaciones);
                nuevaNomina.setTotalNeto(totalNeto);

                // 6. GUARDAR EN BASE DE DATOS
                NominaDAO dao = new NominaDAO();
                boolean exito = dao.agregarNomina(nuevaNomina);

                if (exito) {
                    JOptionPane.showMessageDialog(this, 
                        "Nómina agregada correctamente\n\n" +
                        "Resumen de cálculos automáticos:\n" +
                        "• Empleado ID: " + idEmpleado + "\n" +
                        "• Horas trabajadas: " + totalHorasTrabajadas + "\n" +
                        "• Sueldo base: $" + sueldoBaseEmpleado + "\n" +
                        "• Total prestaciones: $" + totalPrestaciones + "\n" +
                        "• Total neto: $" + totalNeto, 
                        "Éxito", 
                        JOptionPane.INFORMATION_MESSAGE);

                    // 7. LIMPIAR FORMULARIO Y ACTUALIZAR TABLA
                    txtIdEmpleado.setText(""); // Limpiar el único campo del formulario
                    
                    if (onUpdateSuccess != null) {
                        onUpdateSuccess.run(); // Actualiza la tabla principal
                    }
                    parent.dispose(); // Cierra la ventana
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "Error al agregar nómina en la base de datos", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                }

            } catch (NumberFormatException e) {
                // Error si el usuario ingresa texto en el campo ID Empleado
                JOptionPane.showMessageDialog(this, 
                    "Por favor ingrese un ID de empleado válido (solo números)", 
                    "Error de Formato", 
                    JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                // Error general
                JOptionPane.showMessageDialog(this, 
                    "Error inesperado: " + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                e.printStackTrace(); // Para debugging
            }
        });

        // Mostrar el diálogo de confirmación
        confirmacion.mostrar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtIdEmpleado;
    // End of variables declaration//GEN-END:variables
}
