package com.proyectodeprueba.ui.subventanas;


import com.formdev.flatlaf.FlatClientProperties;
import com.proyectodeprueba.ui.subventanas.confirmacion.ConfirmacionDialog;
import java.awt.Frame;
import javax.swing.JOptionPane;
import DAO.PrestacionDAO;
import java.awt.event.ActionEvent;
import models.Prestacion;

/**
 *
 * @author Pablo
 */
public class AgregarPrestacionPanel extends javax.swing.JPanel {
    
    private AgregarDialog parentDialog; // Cambié ModificaDialog por AgregarDialog
    private Runnable onUpdateSuccess;
    
    
    /**
     * Creates new form CrearAsistenciaPanel
     */
    public AgregarPrestacionPanel(AgregarDialog parent, Runnable onUpdate) { // Agregué el parámetro Runnable
        initComponents();
        this.parentDialog = parent;
        this.onUpdateSuccess = onUpdate; // Solo estas dos líneas
        
        // Estilos de los componentes (tu código original)
        txtIdEmpl.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtTipo.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtMonto.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtDescripcion.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        btnAgregar.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        btnAgregar.putClientProperty(FlatClientProperties.BUTTON_TYPE, "roundRect");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtIdEmpl = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(300, 450));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(55, 55, 55));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jLabel1.setBackground(new java.awt.Color(55, 55, 55));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Prestación");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 240));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Id empleado:");
        jLabel5.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel7.add(jLabel5);

        txtIdEmpl.setBackground(new java.awt.Color(216, 216, 216));
        txtIdEmpl.setPreferredSize(new java.awt.Dimension(220, 30));
        txtIdEmpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmplActionPerformed(evt);
            }
        });
        jPanel7.add(txtIdEmpl);

        jPanel2.add(jPanel7);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tipo de prestación:");
        jLabel2.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel5.add(jLabel2);

        txtTipo.setBackground(new java.awt.Color(216, 216, 216));
        txtTipo.setPreferredSize(new java.awt.Dimension(220, 30));
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });
        jPanel5.add(txtTipo);

        jPanel2.add(jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Monto:");
        jLabel3.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel3.add(jLabel3);

        txtMonto.setBackground(new java.awt.Color(216, 216, 216));
        txtMonto.setPreferredSize(new java.awt.Dimension(220, 30));
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        jPanel3.add(txtMonto);

        jPanel2.add(jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descripción:");
        jLabel4.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel6.add(jLabel4);

        txtDescripcion.setBackground(new java.awt.Color(216, 216, 216));
        txtDescripcion.setPreferredSize(new java.awt.Dimension(220, 30));
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jPanel6.add(txtDescripcion);

        jPanel2.add(jPanel6);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        btnAgregar.setBackground(new java.awt.Color(55, 55, 55));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setPreferredSize(new java.awt.Dimension(80, 35));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        jPanel4.add(btnAgregar);

        jPanel2.add(jPanel4);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here: 
        
        try {
        // Validar campos
        String idEmplStr = txtIdEmpl.getText().trim();
        String tipoStr = txtTipo.getText().trim();
        String montoStr = txtMonto.getText().trim();
        String descripcionStr = txtDescripcion.getText().trim();

        if (idEmplStr.isEmpty() || tipoStr.isEmpty() || montoStr.isEmpty() || descripcionStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idEmpleado = Integer.parseInt(idEmplStr);
        java.math.BigDecimal monto = new java.math.BigDecimal(String.valueOf(montoStr));

        // Crear nueva prestacion
        Prestacion nuevaPrestacion = new Prestacion();
        nuevaPrestacion.setIdEmpleado(idEmpleado);
        nuevaPrestacion.setTipoPrestacion(tipoStr);
        nuevaPrestacion.setMonto(monto);
        nuevaPrestacion.setDescripcion(descripcionStr);
        nuevaPrestacion.setFecha(java.time.LocalDateTime.now());

        // Guardar en la base de datos
        PrestacionDAO dao = new PrestacionDAO();
        boolean exito = dao.agregarPrestacion(nuevaPrestacion);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Prestación agregada correctamente.");
            
            // Ejecutar callback de actualización
            if (onUpdateSuccess != null) {
                onUpdateSuccess.run();
            }
            
            // Cerrar diálogo
            parentDialog.dispose();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Error al guardar la prestación.\n\nPosibles causas:\n" +
                "• El empleado con ID " + idEmpleado + " no existe\n" +
                "• Error de conexión a la base de datos\n" +
                "• Datos inválidos", 
                "Error al Agregar Prestación", 
                JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese los valores correctos para ID empleado, tipo de prestación, monto y descripción.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void txtIdEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmplActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdEmpl;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
