/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyectodeprueba.ui.subventanas;

import DAO.NominaDAO;
import com.formdev.flatlaf.FlatClientProperties;
import com.proyectodeprueba.ui.subventanas.confirmacion.ConfirmacionDialog;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo
 */
public class EliminarNominaPanel extends javax.swing.JPanel {
    
    private EliminarDialog parentDialog; // Referencia al diálogo que contiene este panel
    private int idParaEliminar;          // El ID de la nómina que se va a eliminar
    private Runnable onEliminarSuccess;

    /**
     * Creates new form EliminarAsistenciaPanel
     */
    public EliminarNominaPanel(EliminarDialog parent, int idNomina, Runnable onUpdate) {
        initComponents(); // Inicializa componentes visuales

        // Guarda las referencias recibidas en las variables de la clase
        this.parentDialog = parent; 
        this.idParaEliminar = idNomina; 
        this.onEliminarSuccess = onUpdate; 

        // Muestra el ID en el campo de texto y lo deshabilita
        txtIdNomina.setText(String.valueOf(idParaEliminar));
        txtIdNomina.setEditable(false);

        // Aplica tus estilos
        txtIdNomina.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        btnEliminar.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        btnEliminar.putClientProperty(FlatClientProperties.BUTTON_TYPE, "roundRect");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdNomina = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(300, 230));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(55, 55, 55));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar Nómina");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id Nómina:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel3.add(jLabel2);

        txtIdNomina.setBackground(new java.awt.Color(216, 216, 216));
        txtIdNomina.setForeground(new java.awt.Color(0, 0, 0));
        txtIdNomina.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel3.add(txtIdNomina);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        btnEliminar.setBackground(new java.awt.Color(55, 55, 55));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setPreferredSize(new java.awt.Dimension(80, 35));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel4.add(btnEliminar);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(
            this, // El componente padre de este diálogo
            "¿Estás seguro de que deseas eliminar la nómina con ID " + this.idParaEliminar + "?", // El mensaje
            "Confirmar Eliminación", // El título de la ventana
            JOptionPane.YES_NO_OPTION, // Tipo de botones (Sí/No)
            JOptionPane.WARNING_MESSAGE // Ícono de advertencia
        );

        // 2. Si el usuario presiona "Sí" (YES_OPTION)...
        if (respuesta == JOptionPane.YES_OPTION) {
            try {

                NominaDAO dao = new NominaDAO();
                boolean exito = dao.eliminarNomina(this.idParaEliminar);
                
                // 4. Verifica si la eliminación fue exitosa
                if (exito) {
                    // Muestra mensaje de éxito
                    JOptionPane.showMessageDialog(this, "Nómina eliminada correctamente.");

                    // Ejecuta la acción para refrescar la tabla principal (si existe)
                    if (onEliminarSuccess != null) {
                        onEliminarSuccess.run();
                    }

                    // Cierra esta subventana
                    parentDialog.dispose();
                } else {
                    // Muestra mensaje de error si la eliminación falló
                    JOptionPane.showMessageDialog(this, 
                        "Error al eliminar la nómina.\n\nPosibles causas:\n" +
                        "• La nómina no existe\n" +
                        "• Error de base de datos", 
                        "Error de Base de Datos", 
                        JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, 
                    "Error inesperado al eliminar nómina:\n" + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                System.err.println("Excepción al eliminar nómina: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtIdNomina;
    // End of variables declaration//GEN-END:variables
}
