/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyectodeprueba.ui.subventanas;

import DAO.EmpleadoDAO;
import com.formdev.flatlaf.FlatClientProperties;
import com.proyectodeprueba.ui.subventanas.confirmacion.ConfirmacionDialog;
import java.awt.Frame;

/**
 *
 * @author Pablo
 */
public class EliminarEmpleadosPanel extends javax.swing.JPanel {
    
    private EliminarDialog parentDialog;
    private int idParaEliminar;
    private Runnable onEliminarSuccess;

    /**
     * Creates new form EliminarAsistenciaPanel
     */
    public EliminarEmpleadosPanel(EliminarDialog parent, int idEmpleado, Runnable onUpdate) {
        this.parentDialog = parent; // ✅ Asignar correctamente
        initComponents();
        
        this.idParaEliminar = idEmpleado;
        this.onEliminarSuccess = onUpdate;
        
        txtIdEmpleado.setText(String.valueOf(idEmpleado));
        txtIdEmpleado.setEditable(false);
        
        txtIdEmpleado.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        
        btnEliminar.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        btnEliminar.putClientProperty(FlatClientProperties.BUTTON_TYPE, "roundRect");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(300, 230));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(55, 55, 55));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar Empleado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id Empleado:");
        jLabel2.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel3.add(jLabel2);

        txtIdEmpleado.setBackground(new java.awt.Color(216, 216, 216));
        txtIdEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        txtIdEmpleado.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel3.add(txtIdEmpleado);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        btnEliminar.setBackground(new java.awt.Color(55, 55, 55));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setPreferredSize(new java.awt.Dimension(80, 35));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel4.add(btnEliminar);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        // Paste this code inside the new btnEliminarMouseClicked method

// 1. Pide confirmación al usuario
int respuesta = javax.swing.JOptionPane.showConfirmDialog(
    this, 
    "⚠️ ADVERTENCIA ⚠️\n\n" +
    "¿Estás seguro de que deseas eliminar al empleado con ID " + this.idParaEliminar + "?\n\n" +
    "Esto eliminará PERMANENTEMENTE:\n" +
    "• El empleado\n" +
    "• Todas sus asistencias\n" +
    "• Todas sus nóminas\n" +
    "• Todas sus prestaciones\n\n" +
    "Esta acción NO se puede deshacer.", 
    "⚠️ Confirmar Eliminación Completa", 
    javax.swing.JOptionPane.YES_NO_OPTION,
    javax.swing.JOptionPane.WARNING_MESSAGE
);

// 2. Si confirma, llama al DAO
if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
    try {
        EmpleadoDAO dao = new EmpleadoDAO();
        boolean exito = dao.eliminarEmpleado(this.idParaEliminar);

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente.");
            
            // Avisa a la tabla principal que se actualice
            if (onEliminarSuccess != null) {
                onEliminarSuccess.run();
            }
            
            // Cierra esta subventana
            if (parentDialog != null) {
                parentDialog.dispose();
            } else {
                System.err.println("Advertencia: parentDialog es null, no se puede cerrar el diálogo");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al eliminar el empleado.\n\nPosibles causas:\n" +
                "• El empleado no existe\n" +
                "• Error en la base de datos\n" +
                "• Problema de permisos", 
                "Error de Base de Datos", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error inesperado al eliminar empleado:\n" + e.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        System.err.println("Excepción al eliminar empleado: " + e.getMessage());
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_btnEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtIdEmpleado;
    // End of variables declaration//GEN-END:variables
}
