/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyectodeprueba.ui.subventanas;

import com.formdev.flatlaf.FlatClientProperties;
import com.proyectodeprueba.ui.subventanas.confirmacion.ConfirmacionDialog;
import java.awt.Frame;
import DAO.NominaDAO;
import models.Nomina;

/**
 *
 * @author Pablo
 */
public class ModificarNominaPanel extends javax.swing.JPanel {

     private ModificarDialog parent;
     private int idNomina;
     private Runnable onUpdateSuccess;
    
    /**
     * Creates new form AgregarNominaPanel
     */
    public ModificarNominaPanel(ModificarDialog parent, int idNom, int idEmpl, int horas, String fecha, 
            String totPrest, String totNeto, String sueldoBase, Runnable onUpdate) {
        initComponents();
        this.parent = parent;
        this.idNomina = idNom;
        this.onUpdateSuccess = onUpdate;
        
        // Rellenar los campos
        txtIdNomina.setText(String.valueOf(idNom));
        txtIdEmpleado.setText(String.valueOf(idEmpl));
        txtHoras.setText(String.valueOf(horas));
        txtFecha.setText(fecha);
        txtTotalPrest.setText(totPrest);
        txtTotalNeto.setText(totNeto);
        txtSueldoBase.setText(sueldoBase);
        
        // Hacer que los id no se puedan editar
        txtIdNomina.setEditable(false);
        txtIdEmpleado.setEditable(false);
        
        txtIdNomina.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtIdEmpleado.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtHoras.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtTotalPrest.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtTotalNeto.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtFecha.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        txtSueldoBase.putClientProperty(FlatClientProperties.STYLE, "arc:15; borderWidth: 0");
        
        btnMod.putClientProperty(FlatClientProperties.STYLE, "arc:20; focusWidth:0; borderWidth:0");
        btnMod.putClientProperty(FlatClientProperties.BUTTON_TYPE, "roundRect");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdNomina = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalPrest = new javax.swing.JTextField();
        Right = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTotalNeto = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSueldoBase = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnMod = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 475));
        setLayout(new java.awt.BorderLayout());

        Top.setBackground(new java.awt.Color(55, 55, 55));
        Top.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Nómina");

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(Top, java.awt.BorderLayout.NORTH);

        Left.setBackground(new java.awt.Color(255, 255, 255));
        Left.setPreferredSize(new java.awt.Dimension(300, 390));
        Left.setLayout(new java.awt.GridLayout(5, 1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id Nómina:");
        jLabel2.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel3.add(jLabel2);

        txtIdNomina.setBackground(new java.awt.Color(216, 216, 216));
        txtIdNomina.setForeground(new java.awt.Color(0, 0, 0));
        txtIdNomina.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel3.add(txtIdNomina);

        Left.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Id Empleado:");
        jLabel3.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel4.add(jLabel3);

        txtIdEmpleado.setBackground(new java.awt.Color(216, 216, 216));
        txtIdEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        txtIdEmpleado.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel4.add(txtIdEmpleado);

        Left.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Horas Trabajadas:");
        jLabel4.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel5.add(jLabel4);

        txtHoras.setBackground(new java.awt.Color(216, 216, 216));
        txtHoras.setForeground(new java.awt.Color(0, 0, 0));
        txtHoras.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel5.add(txtHoras);

        Left.add(jPanel5);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha:");
        jLabel7.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel10.add(jLabel7);

        txtFecha.setBackground(new java.awt.Color(216, 216, 216));
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel10.add(txtFecha);

        Left.add(jPanel10);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total Prestaciones:");
        jLabel5.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel6.add(jLabel5);

        txtTotalPrest.setBackground(new java.awt.Color(216, 216, 216));
        txtTotalPrest.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalPrest.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel6.add(txtTotalPrest);

        Left.add(jPanel6);

        add(Left, java.awt.BorderLayout.LINE_START);

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(300, 390));
        Right.setLayout(new java.awt.GridLayout(5, 1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Total Neto:");
        jLabel6.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel9.add(jLabel6);

        txtTotalNeto.setBackground(new java.awt.Color(216, 216, 216));
        txtTotalNeto.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalNeto.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel9.add(txtTotalNeto);

        Right.add(jPanel9);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Sueldo Base:");
        jLabel8.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel11.add(jLabel8);

        txtSueldoBase.setBackground(new java.awt.Color(216, 216, 216));
        txtSueldoBase.setForeground(new java.awt.Color(0, 0, 0));
        txtSueldoBase.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel11.add(txtSueldoBase);

        Right.add(jPanel11);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btnMod.setBackground(new java.awt.Color(55, 55, 55));
        btnMod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMod.setForeground(new java.awt.Color(255, 255, 255));
        btnMod.setText("Modificar");
        btnMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMod.setPreferredSize(new java.awt.Dimension(100, 35));
        btnMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModMouseClicked(evt);
            }
        });
        jPanel8.add(btnMod);

        Right.add(jPanel8);

        add(Right, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModMouseClicked
        // Crear la ventana de confirmación
        ConfirmacionDialog confirmacion = new ConfirmacionDialog((Frame) parent.getParent(), true);
        
        // Configurar la acción a ejecutar si el usuario confirma
        confirmacion.setOnConfirmar(() -> {
            // Aquí va la lógica para actualizar los datos
            try {
                // Obtener los valores de los campos
                int idEmpleado = Integer.parseInt(txtIdEmpleado.getText().trim());
                int horasTrabajadas = Integer.parseInt(txtHoras.getText().trim());
                String fechaTexto = txtFecha.getText().trim();
                java.math.BigDecimal sueldoBase = new java.math.BigDecimal(txtSueldoBase.getText().trim());
                java.math.BigDecimal totalPrestaciones = new java.math.BigDecimal(txtTotalPrest.getText().trim());
                java.math.BigDecimal totalNeto = new java.math.BigDecimal(txtTotalNeto.getText().trim());
                
                // Crear objeto Nomina con los datos actualizados
                Nomina nominaActualizada = new Nomina();
                nominaActualizada.setIdNomina(idNomina);
                nominaActualizada.setIdEmpleado(idEmpleado);
                nominaActualizada.setTotalHorasTrabajadas(horasTrabajadas);
                nominaActualizada.setFecha(java.time.LocalDateTime.parse(fechaTexto.replace(" ", "T")));
                nominaActualizada.setSueldoBase(sueldoBase);
                nominaActualizada.setTotalPrestaciones(totalPrestaciones);
                nominaActualizada.setTotalNeto(totalNeto);
                
                // Actualizar en la base de datos
                NominaDAO dao = new NominaDAO();
                boolean exito = dao.modificarNomina(nominaActualizada);
                
                if (exito) {
                    // Mostrar mensaje de éxito
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "Nómina modificada exitosamente", 
                        "Éxito", 
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    
                    // Cerrar el diálogo padre y actualizar la tabla
                    if (onUpdateSuccess != null) {
                        onUpdateSuccess.run();
                    }
                    parent.dispose();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "No se pudo modificar la nómina. Inténtelo nuevamente.", 
                        "Error", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error en el formato de los números. Por favor, verifique los valores.", 
                    "Error de formato", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error al modificar la nómina: " + e.getMessage(), 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        });
        
        // Mostrar la ventana de confirmación
        confirmacion.mostrar();
    }//GEN-LAST:event_btnModMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel Top;
    private javax.swing.JButton btnMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdNomina;
    private javax.swing.JTextField txtSueldoBase;
    private javax.swing.JTextField txtTotalNeto;
    private javax.swing.JTextField txtTotalPrest;
    // End of variables declaration//GEN-END:variables
}
